channels:
  - conda-forge
  - bioconda
  - r
  - defaults
dependencies:
  - snakemake>=3.9.0
  - python>=3.8,<3.12
  - pip
  - biopython
  - seqkit 
  - wget 
  - sra-tools
  - blast=2.10
  - gcc
  - pip:
    - matplotlib>3.3.2
    - pandas
    - tmhmm.py